### ISSUE TITLE
Website URL is down!

### ISSUE THREAD

**Issue by mazen-kasser** [cparker15/csv-to-json#7]
Can you please relaunch your website at (http://www.cparker15.com/code/utilities/csv-to-json/) as I am depending on your tool to convert events from CSV to JSON format... Thanks

**Comment by sdeering** [comment]
second that.

**Comment by hhzl** [comment]
@sdeering , what about following the [README](https://github.com/cparker15/csv-to-json/blob/master/README.md) and building it so that you can have your own version on your web site (or local intranet)?

```
      git clone https://github.com/cparker15/csv-to-json.git
      cd csv-to-json/
      npm install
      grunt
```

**Result** is in _dist_ subdirectory. Copy all the files there to a place on your own web site.

In case you need more instructions than is given in the README don't hesitate to ask.

**Comment by hhzl** [comment]
**Alternative** Start using 
https://github.com/mholt/PapaParse
which is maintained. 

This is **not** a statement about the quality of the code of this repository which I did not check. It is just a remark that it is easier to go with a maintained code base. And the PapaParse web site offers a conversion function.
